import { defineConfig } from 'vite';
import { resolve } from 'node:path';

// Three static language versions: / (ru), /uz/, /en/ — generated by scripts/i18n.mjs
export default defineConfig({
  build: {
    rollupOptions: {
      input: {
        ru: resolve(import.meta.dirname, 'index.html'),
        uz: resolve(import.meta.dirname, 'uz/index.html'),
        en: resolve(import.meta.dirname, 'en/index.html'),
      },
    },
  },
});
